// Generated by scripts/tiktok/fixtures.py generate.
package app.morphe.patches.shared.compat

import app.morphe.patcher.patch.AppTarget

internal object VerifiedTikTokVersions {
    val targets = listOf(
        AppTarget(version = "46.7.3", versionCode = 2024607030),
    )
}
