#!/usr/bin/env python3
"""Exact fixture identities; candidate entries never expand selectable compatibility."""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT/'fixtures/tiktok/fixtures.json'
GENERATED = ROOT/'patches/src/main/kotlin/app/morphe/patches/shared/compat/VerifiedTikTokVersions.kt'


def fixtures(path=MANIFEST):
    data = json.loads(path.read_text())
    if data.get('schema') != 1 or not data.get('fixtures'):
        raise ValueError('Nonempty fixture manifest schema 1 required')
    seen = set()
    for f in data['fixtures']:
        if f['id'] in seen or not re.fullmatch('[a-z0-9.-]+', f['id']):
            raise ValueError('Duplicate or unsafe fixture id')
        seen.add(f['id'])
        if f['package'] != 'com.zhiliaoapp.musically' or not re.fullmatch(r'\d+(?:\.\d+)+', f['version']):
            raise ValueError('Exact global package/version required')
        if not re.fullmatch('[a-f0-9]{64}', f['sha256']) or not f.get('provenance'):
            raise ValueError('Exact SHA-256 and provenance required')
        if not f.get('url', '').startswith('https://') or not isinstance(f['versionCode'], int):
            raise ValueError('HTTPS URL and version code required')
        if f.get('selectable'):
            q = f.get('qualification', {})
            if not re.fullmatch('[a-f0-9]{40}', q.get('head', '')) or not all(q.get(k) for k in ('acceptanceRun', 'discoveryRun', 'runtime')):
                raise ValueError('Selectable fixture needs same-head acceptance, discovery and runtime evidence')
        yield f


def select(identity):
    found = [f for f in fixtures() if f['id'] == identity]
    if len(found) != 1: raise ValueError('Expected one fixture: ' + identity)
    return found[0]


def verify(fixture, path, metadata=True):
    with path.open('rb') as stream: actual = hashlib.file_digest(stream, 'sha256').hexdigest()
    if actual != fixture['sha256']: raise ValueError(f"Fixture SHA-256 mismatch: expected {fixture['sha256']}, got {actual}")
    if metadata:
        from loguru import logger
        logger.remove()
        from androguard.core.apk import APK
        apk = APK(str(path))
        identity = (apk.get_package(), apk.get_androidversion_name(), int(apk.get_androidversion_code()))
        if identity != (fixture['package'], fixture['version'], fixture['versionCode']): raise ValueError(f'APK identity mismatch: {identity}')
    return actual


def generated():
    enabled = [f for f in fixtures() if f.get('selectable')]
    if not enabled or len({f['version'] for f in enabled}) != len(enabled): raise ValueError('One selectable fixture per version required')
    entries = ',\n'.join(f'        AppTarget(version = "{f["version"]}", versionCode = {f["versionCode"]})' for f in enabled)
    return '// Generated by scripts/tiktok/fixtures.py generate.\npackage app.morphe.patches.shared.compat\n\nimport app.morphe.patcher.patch.AppTarget\n\ninternal object VerifiedTikTokVersions {\n    val targets = listOf(\n' + entries + ',\n    )\n}\n'


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('command', choices=('matrix','fetch','verify','generate'))
    p.add_argument('--fixture'); p.add_argument('--apk',type=Path); p.add_argument('--check',action='store_true')
    a=p.parse_args()
    if a.command == 'matrix': print(json.dumps({'include':list(fixtures())},separators=(',',':')))
    elif a.command == 'generate':
        text=generated()
        if a.check:
            if not GENERATED.exists() or GENERATED.read_text()!=text: raise SystemExit('Compatibility metadata stale; run fixtures.py generate')
        else: GENERATED.write_text(text)
    else:
        f=select(a.fixture)
        if a.command=='fetch':
            a.apk.parent.mkdir(parents=True,exist_ok=True)
            subprocess.run(['curl','-fLsS','--proto','=https','--proto-redir','=https','--retry','3','--max-time','300',f['url'],'-o',str(a.apk)],check=True)
        print(verify(f,a.apk))
if __name__=='__main__': main()
